# Generated by Django 4.2.1 on 2023-05-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=12)),
                ("message", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
