# Generated by Django 4.2.1 on 2023-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("place_id", models.AutoField(primary_key=True, serialize=False)),
                ("place_type", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField()),
                ("address", models.TextField()),
                ("images", models.ImageField(default="", upload_to="media/images")),
            ],
        ),
    ]
